version: '3.1'

services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    restart: always

  nimbus:
    image: storm
    networks:
      - storm-network
    container_name: nimbus
    command: storm nimbus
    depends_on:
      - zookeeper
    links:
      - zookeeper
    restart: always
    ports:
      - 6627:6627

  ui:
    image: storm
    container_name: nimbus-ui
    command: storm ui
    depends_on:
      - zookeeper
      - nimbus
    links:
      - zookeeper
      - nimbus
    restart: always
    ports:
      - 8080:8080 

  supervisor:
    image: storm
    container_name: supervisor
    command: storm supervisor
    depends_on:
      - nimbus
      - zookeeper
    links:
      - nimbus
      - zookeeper
    restart: always

networks:
  storm-network:
    external: true